
:name: chevdor/srtool
:rsversion: nightly-2019-12-07
:toc:
:sectnums:

= Substrate Runtime Toolbox: srtool

== Intro

srtool is a collection of dockerized tools helping with https://substrate.dev[Substrate] & https://polkadot.network[Polkadot] Runtime development.

It especially helps with building and verifying Wasm Runtime Blobs. 
  
The Docker image is `{name}`. You can find it at https://hub.docker.com/r/{name}.

== Install

=== Pull image

[subs="attributes+"]
----
    docker pull {name}:<version> # <1>
----

<1> where `<version>` is the rustc version you want to use.

...or just skip that step, the right image will be fetched at first run.

=== Create alias    

Creating an alias helps hiding the docker complexity behind one simple command.

.Recommended options
Here is the recommended option:

[subs="attributes+"]
----
    export RUSTC_VERSION={rsversion}; export PACKAGE=polkadot-runtime; alias srtool='docker run --rm -it -e PACKAGE=$PACKAGE -v $PWD:/build -v /tmp/cargo:/cargo-home chevdor/srtool:$RUSTC_VERSION'
----

The command to invoke a build will then be `srtool build`.

.Flexible option for advanced usage
If you want flexibility:

[subs="attributes+"]
----
    function srtool() { docker run --rm -it -e PACKAGE=$1 -v $PWD:/build -v /tmp/cargo:/cargo-home chevdor/srtool:$2 $3; }
----

The command to invoke a build will then be `srtool <package> <rust_version> build`. For instance:

[subs="attributes+"]
----
    srtool my-super-runtime {rsversion} build
    srtool polkadot-runtime nightly-2019-12-05 build
----

You likely want to make this persistent with:

[subs="attributes+"]
----
    echo "export RUSTC_VERSION={rsversion}; export PACKAGE=polkadot-runtime; alias srtool='docker run --rm -it -e PACKAGE=$PACKAGE -v $PWD:/build -v /tmp/cargo:/cargo-home chevdor/srtool:$RUSTC_VERSION'" >> ~/.bash_profile && source ~/.bash_profile
----

If you wish to see more (it takes a little longer), you may set the `VERBOSE` ENV variable:

[subs="attributes+"]
----
    export RUSTC_VERSION={rsversion}; export PACKAGE=polkadot-runtime; alias srtool='docker run --rm -it -e PACKAGE=$PACKAGE -e VERBOSE=1 -v $PWD:/build -v /tmp/cargo:/cargo-home chevdor/srtool:$RUSTC_VERSION'
----

NOTE: The part `-v /tmp/cargo:/cargo-home` exposes the docker container's cargo cache on your local machine. This helps making subsequent builds faster.

== Use

Now that you defined the srtool alias, you can use it as shown below:

.See the help
    srtool help

.Build the runtime
    srtool build

.Typical run

Invoking `srtool build` with:

    $ srtool build

Looks like this:

[subs="attributes+"]
----
    🧰 Substrate Runtime Toolbox 🧰
    🏗  Building polkadot-runtime as release
    ⏳ That can take a little while, be patient... Subsequent builds will be faster.
        Finished release [optimized] target(s) in 37.43s

    real	0m37.931s
    user	0m1.560s
    sys	0m3.220s
    ✨ Your Substrate WASM Runtime is ready! ✨
    Summary:
    Used rustc {rsversion} (4560ea788 2019-11-04)
    Wasm   : ./srtool/release/wbuild/polkadot-runtime/polkadot_runtime.compact.wasm
    Content: 0x0061736d0100000001a4022b60037f7f...3435663020323031392d31322d303429
    Size   : 1.1M
    SHA256 : d5930520676994fc55a29c547f0159ea860cb46edd710a5be35e62565af1ad8b
----

.Advanced usage
if you feel fancy, you may also:

    srtool bash

and look around the /srtool folder

== Build the Docker image

While you don't have to build the image yourself, you still may!

First you may want to double check what rustc versions are available as you will HAVE to build an image for a given version:

    rustup check

So say you want to build a builder for rustc nightly-2019-12-07:

[subs="attributes+"]
----
    RUSTC_VERSION=nightly-2019-12-07 && docker build --build-arg RUSTC_VERSION=$RUSTC_VERSION -t chevdor/srtool:$RUSTC_VERSION .
----