#!/usr/bin/env bash

# If the user sends a SIGINT, we want to exit the entire script
trap "exit" INT

# This is where docker expects our substrate/polkadot repo to be
cd /build

echo "🧰 Substrate Runtime Toolbox 🧰"
echo "        - by Chevdor -"

# srtool only makes sense when called from a Cargo folder so we check that
if [ ! -f Cargo.toml ]; then
    echo "  !!! The folder on your host computer does not look like a Cargo project. Are you really in your repo?"
    exit 1
fi

if [ ! -z "$VERBOSE" ]; then
    echo "Checking cache size. Give it a few seconds..."
    echo -e "📦 Cache size:" `du -sh $HOME/.cargo`
fi

echo -e "🏗  Building $PACKAGE as $PROFILE using" `rustc -V`
echo -e "⏳ That can take a little while, be patient... subsequent builds will be faster."

# Build the runtime and time it :)
CMD="cargo build --$PROFILE -p $PACKAGE --target-dir srtool"
if [ ! -z "$VERBOSE" ]; then
    time $CMD
else
    $CMD
fi

# The following would be nice but not in rust stable yet
#--out-dir srtool-out

echo "✨ Your Substrate WASM Runtime is ready! ✨"

#WASM=`find . -type f -name *.wasm | grep $PROFILE | grep -v deps | grep compact | head -1`
WASM=`find ./srtool/$PROFILE/wbuild/$PACKAGE/*.compact.wasm`
HASH=`shasum -a 256 $WASM | awk '{print $1}'`

SIZE=`wc -c < $WASM`
LENGTH=16
SKIP=`echo $(($SIZE-$LENGTH))`
# Some magic to show the first and last bytes of the blog as the UI does
PREVIEW=`printf "0x"; hexdump -n $LENGTH -ve '1/1 "%.2x"' $WASM; printf "..."; hexdump -n $LENGTH -s $SKIP -ve '1/1 "%.2x"' $WASM`

YELLOW='\033[0;33m'
NC='\033[0m'
MB=`du -sh $WASM | awk '{print $1}'`
SZ=`du -s $WASM | awk '{print $1}'`

echo "Summary:"
echo "  Size    : $MB ($SZ)" 
echo "  Content : $PREVIEW" 
printf "  SHA256  : ${YELLOW}$HASH${NC}\n" 
echo "  Wasm    : $WASM"
