name: Manual Build - Cumulus

env:
  SUBWASM_VERSION: 0.17.0

on:
  workflow_dispatch:
    inputs:
      srtool_tag:
        description: The SRTOOL tag to use
        default: 1.60.0
        required: false
      ref:
        description: The ref to be used for the repo
        default: master
        required: false
  schedule:
    - cron: "00 03 * * 1" # 3AM weekly on mondays

jobs:
  build:
    name: Build ${{ matrix.chain }} ${{ github.event.inputs.ref }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - category: contracts
            runtime: contracts-rococo
          - category: assets
            runtime: statemint
          - category: starters
            runtime: shell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: paritytech/cumulus
          ref: ${{ github.event.inputs.ref }}
          fetch-depth: 0

      - name: Srtool build
        id: srtool_build
        uses: chevdor/srtool-actions@v0.4.0
        with:
          runtime: ${{ matrix.runtime }}
          tag: ${{ github.event.inputs.srtool_tag }}
          runtime_dir: parachains/runtimes/${{ matrix.category }}/${{ matrix.runtime }}

      - name: Summary
        run: |
          echo '${{ steps.srtool_build.outputs.json }}' | jq > ${{ matrix.runtime }}-srtool-digest.json
          cat ${{ matrix.runtime }}-srtool-digest.json
          echo "Runtime location: ${{ steps.srtool_build.outputs.wasm }}"

      # it takes a while to build the runtime, so let's save the artifact as soon as we have it
      - name: Archive Artifacts for ${{ matrix.runtime }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.runtime }}-runtime
          path: |
            ${{ steps.srtool_build.outputs.wasm }}
            ${{ steps.srtool_build.outputs.wasm_compressed }}
            ${{ matrix.runtime }}-srtool-digest.json

      # We now get extra information thanks to subwasm
      - name: Install subwasm ${{ env.SUBWASM_VERSION }}
        run: |
          wget https://github.com/chevdor/subwasm/releases/download/v${{ env.SUBWASM_VERSION }}/subwasm_linux_amd64_v${{ env.SUBWASM_VERSION }}.deb
          sudo dpkg -i subwasm_linux_amd64_v${{ env.SUBWASM_VERSION }}.deb
          subwasm --version
      - name: Show Runtime information
        run: |
          subwasm info ${{ steps.srtool_build.outputs.wasm }}
          subwasm info ${{ steps.srtool_build.outputs.wasm_compressed }}
          subwasm --json info ${{ steps.srtool_build.outputs.wasm }} > ${{ matrix.runtime }}-info.json
          subwasm --json info ${{ steps.srtool_build.outputs.wasm_compressed }} > ${{ matrix.runtime }}-info_compressed.json
      - name: Extract the metadata
        run: |
          subwasm meta ${{ steps.srtool_build.outputs.wasm }}
          subwasm --json meta ${{ steps.srtool_build.outputs.wasm }} > ${{ matrix.runtime }}-metadata.json
      - name: Check the metadata diff
        run: |
          subwasm diff ${{ steps.srtool_build.outputs.wasm }} --chain-b ${{ matrix.runtime }} | tee ${{ matrix.runtime }}-diff.txt

      - name: Archive Subwasm results
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.runtime }}-runtime
          path: |
            ${{ matrix.runtime }}-info.json
            ${{ matrix.runtime }}-info_compressed.json
            ${{ matrix.runtime }}-metadata.json
            ${{ matrix.runtime }}-diff.txt
